// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
// first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
// even-valued terms.
// Answer:  4613732
// Completed on Sun, 05 May 2024, 19:35

package main

import "fmt"

func fibonacci() func() int {
	a := 0
	b := 1
	i := 0
	return func() int {
		if i == 0 {
			i++
			return a
		} else if i == 1 {
			i++
			return b
		} else {
			i++
			a, b = b, a+b
			return b
		}
	}
}

func main() {
	result := 0
	fib_num := fibonacci()

	for {
		value := fib_num()
		if value > 4000000 {
			break
		}
		if value%2 == 0 {
			result += value
		}
	}
	fmt.Println(result)
}
