"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
Answer:  4613732
Completed on Tue, 21 Dec 2021, 08:17
"""


def fibonacci(ceil_number):
    fibonacci_list = [1, 2]
    while True:
        if sum(fibonacci_list[-2:]) < ceil_number:
            fibonacci_list.append(sum(fibonacci_list[-2:]))
        else:
            return fibonacci_list

def main():
    fibonacci_even_list = []
    fibonacci_list = fibonacci(4000000)

    for number in fibonacci_list:
        if number % 2 == 0:
            fibonacci_even_list.append(number)

    print(sum(fibonacci_even_list))

if __name__ == '__main__':
    main()